name: Build and Publish

on:
  push:
    branches: [ main ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    env:
      Scripts: ./.github/workflows/scripts

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Copy frontend build artifacts to dotnet app
      run: |
        mkdir -p src/QueryPressure.UI/dist
        cp -r frontend/dist/* src/QueryPressure.UI/dist/

    - name: Build and publish dotnet app
      shell: pwsh
      run: |
        ${{ env.Scripts }}/DotnetPublish.ps1 -OutputSubfolder linux -Runtime linux-x64
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          src/QueryPressure.UI/.out/linux/QueryPressure.UI
          
          
  deploy: # Azure AppService Deploy
    runs-on: ubuntu-latest
    needs: build-and-publish
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'QueryPressure'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E14A3C1B94CC43ACB07F30DAE34A7CAC }}
          package: .
